set(SOURCES
	include/Console.h
	include/Graphics.h
	include/Hooks.h
	include/ImGui/Fonts/BGSFonts.h
	include/ImGui/Fonts/IconsFontAwesome6.h
	include/ImGui/Fonts/Manager.h
	include/ImGui/FormComboBox.h
	include/ImGui/Graphics.h
	include/ImGui/Renderer.h
	include/ImGui/Styles.h
	include/ImGui/Util.h
	include/ImGui/Widgets.h
	include/Input.h
	include/PCH.h
	include/PhotoMode/Hotkeys.h
	include/PhotoMode/Manager.h
	include/PhotoMode/Tabs/Camera.h
	include/PhotoMode/Tabs/Character.h
	include/PhotoMode/Tabs/Filters.h
	include/PhotoMode/Tabs/Overlays.h
	include/PhotoMode/Tabs/Time.h
	include/RE.h
	include/Screenshots/Manager.h
	include/Settings.h
	include/Translation.h
	src/Console.cpp
	src/Graphics.cpp
	src/Hooks.cpp
	src/ImGui/Fonts/Manager.cpp
	src/ImGui/Graphics.cpp
	src/ImGui/Renderer.cpp
	src/ImGui/Styles.cpp
	src/ImGui/Util.cpp
	src/ImGui/Widgets.cpp
	src/Input.cpp
	src/PCH.cpp
	src/PhotoMode/Hotkeys.cpp
	src/PhotoMode/Manager.cpp
	src/PhotoMode/Tabs/Camera.cpp
	src/PhotoMode/Tabs/Character.cpp
	src/PhotoMode/Tabs/Filters.cpp
	src/PhotoMode/Tabs/Overlays.cpp
	src/PhotoMode/Tabs/Time.cpp
	src/Screenshots/Manager.cpp
	src/Settings.cpp
	src/Translation.cpp
	src/main.cpp
)
